tasks:
  - name: jpeg-xl
    command: cjxl --lossless_jpeg=1 {{.folder}}/{{.name}}.{{.extension}} {{.folder}}/{{.name}}-new.jxl && rm {{.folder}}/{{.name}}.{{.extension}}
    extensions:
      - jpeg
      - jpg
      - png
      - pgx
      - pam
      - pnm
      - pgm
      - ppm
      - pfm
      - gif
      - exr

  - name: caesium
    command: caesiumclt --keep-dates --exif --quality=0 --output={{.folder}} {{.folder}}/{{.name}}.{{.extension}}
    extensions:
      - jpeg
      - jpg
      - png
      - tiff
      - tif
      - webp
      - gif

  # Note not all image formats accepted by immich are supported by jpeg-xl and caesium so passthrough the rest as-is.
  # https://immich.app/docs/features/supported-formats/
  - name: passthrough-images
    command: ""
    extensions:
      - avif
      - bmp
      - heic
      - heif
      - insp
      - jxl
      - psd
      - raw
      - rw2
      - svg

  # Not aware of any lossless video conversion that will result in a smaller file size than the original so keep them as-is.
  # Check out personal config folder for lossy video conversion.
  - name: passthrough-videos
    command: ""
    extensions:
      - 3gp
      - 3gpp
      - avi
      - flv
      - m4v
      - mkv
      - mts
      - m2ts
      - m2t
      - mp4
      - insv
      - mpg
      - mpe
      - mpeg
      - mov
      - webm
      - wmv